# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    
    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        files: |
          yarn.lock

    - name: Run step when yarn.lock change
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
        yarn run build

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: 'dist'
        message: 'Update heic2any.js'
